-- challenge_assignments 데이터
INSERT INTO challenge_assignments (
    id,
    assigned_date,
    challenge_status,
    origin,
    user_id,
    challenge_master_id,
    log_date,
    emotion,
    created_at,
    updated_at
) VALUES
-- Alice (user_id: 1)
(1, now() - interval '1 day', 'COMPLETED', 'RECOMMENDED', 1, 1, now() - interval '1 day', 5, now() - interval '1 day', now() - interval '1 day'),
(11, now() - interval '7 days', 'COMPLETED', 'RECOMMENDED', 1, 4, now() - interval '7 days', 4, now() - interval '7 days', now() - interval '7 days'),
(12, now() - interval '5 days', 'COMPLETED', 'SELF', 1, 2, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(13, now() - interval '3 days', 'COMPLETED', 'RECOMMENDED', 1, 8, now() - interval '3 days', 4, now() - interval '3 days', now() - interval '3 days'),
(8, now(), 'ASSIGNED', 'SELF', 1, 7, NULL, NULL, now(), now()),
(31, now() - interval '14 days', 'COMPLETED', 'RECOMMENDED', 1, 3, now() - interval '14 days', 5, now() - interval '14 days', now() - interval '14 days'),
(32, now() - interval '12 days', 'COMPLETED', 'SELF', 1, 5, now() - interval '12 days', 4, now() - interval '12 days', now() - interval '12 days'),
(33, now() - interval '10 days', 'COMPLETED', 'RECOMMENDED', 1, 6, now() - interval '10 days', 5, now() - interval '10 days', now() - interval '10 days'),
(34, now() - interval '8 days', 'COMPLETED', 'SELF', 1, 9, now() - interval '8 days', 5, now() - interval '8 days', now() - interval '8 days'),
(35, now() - interval '6 days', 'ASSIGNED', 'RECOMMENDED', 1, 8, NULL, NULL, now() - interval '6 days', now() - interval '6 days'),
(81, now() - interval '21 days', 'COMPLETED', 'SELF', 1, 10, now() - interval '21 days', 4, now() - interval '21 days', now() - interval '21 days'),
(82, now() - interval '19 days', 'COMPLETED', 'RECOMMENDED', 1, 5, now() - interval '19 days', 4, now() - interval '19 days', now() - interval '19 days'),
(83, now() - interval '17 days', 'ASSIGNED', 'SELF', 1, 3, NULL, NULL, now() - interval '17 days', now() - interval '17 days'),
(84, now() - interval '15 days', 'COMPLETED', 'RECOMMENDED', 1, 7, now() - interval '15 days', 3, now() - interval '15 days', now() - interval '15 days'),
(85, now() - interval '13 days', 'COMPLETED', 'SELF', 1, 4, now() - interval '13 days', 4, now() - interval '13 days', now() - interval '13 days'),

-- Bob (user_id: 2)
(2, now(), 'ASSIGNED', 'RECOMMENDED', 2, 3, NULL, NULL, now(), now()),
(14, now() - interval '10 days', 'COMPLETED', 'SELF', 2, 1, now() - interval '10 days', 4, now() - interval '10 days', now() - interval '10 days'),
(15, now() - interval '6 days', 'COMPLETED', 'RECOMMENDED', 2, 6, now() - interval '6 days', 5, now() - interval '6 days', now() - interval '6 days'),
(16, now() - interval '2 days', 'ASSIGNED', 'SELF', 2, 5, NULL, NULL, now() - interval '2 days', now() - interval '2 days'),
(9, now() - interval '1 day', 'COMPLETED', 'RECOMMENDED', 2, 2, now() - interval '1 day', 4, now() - interval '1 day', now() - interval '1 day'),
(36, now() - interval '15 days', 'COMPLETED', 'RECOMMENDED', 2, 4, now() - interval '15 days', 4, now() - interval '15 days', now() - interval '15 days'),
(37, now() - interval '13 days', 'COMPLETED', 'SELF', 2, 7, now() - interval '13 days', 3, now() - interval '13 days', now() - interval '13 days'),
(38, now() - interval '11 days', 'COMPLETED', 'RECOMMENDED', 2, 10, now() - interval '11 days', 5, now() - interval '11 days', now() - interval '11 days'),
(39, now() - interval '9 days', 'COMPLETED', 'SELF', 2, 9, now() - interval '9 days', 5, now() - interval '9 days', now() - interval '9 days'),
(40, now() - interval '4 days', 'COMPLETED', 'RECOMMENDED', 2, 8, now() - interval '4 days', 4, now() - interval '4 days', now() - interval '4 days'),
(86, now() - interval '22 days', 'COMPLETED', 'RECOMMENDED', 2, 8, now() - interval '22 days', 4, now() - interval '22 days', now() - interval '22 days'),
(87, now() - interval '20 days', 'COMPLETED', 'SELF', 2, 4, now() - interval '20 days', 4, now() - interval '20 days', now() - interval '20 days'),
(88, now() - interval '18 days', 'COMPLETED', 'RECOMMENDED', 2, 7, now() - interval '18 days', 3, now() - interval '18 days', now() - interval '18 days'),
(89, now() - interval '16 days', 'ASSIGNED', 'SELF', 2, 6, NULL, NULL, now() - interval '16 days', now() - interval '16 days'),
(90, now() - interval '14 days', 'COMPLETED', 'RECOMMENDED', 2, 1, now() - interval '14 days', 4, now() - interval '14 days', now() - interval '14 days'),

-- Charlie (user_id: 3)
(3, now() - interval '30 days', 'ASSIGNED', 'SELF', 3, 2, NULL, NULL, now() - interval '30 days', now() - interval '30 days'),
(41, now() - interval '25 days', 'COMPLETED', 'RECOMMENDED', 3, 1, now() - interval '25 days', 4, now() - interval '25 days', now() - interval '25 days'),
(42, now() - interval '20 days', 'ASSIGNED', 'SELF', 3, 7, NULL, NULL, now() - interval '20 days', now() - interval '20 days'),
(43, now() - interval '15 days', 'COMPLETED', 'RECOMMENDED', 3, 4, now() - interval '15 days', 4, now() - interval '15 days', now() - interval '15 days'),
(44, now() - interval '10 days', 'ASSIGNED', 'SELF', 3, 3, NULL, NULL, now() - interval '10 days', now() - interval '10 days'),
(45, now() - interval '5 days', 'COMPLETED', 'RECOMMENDED', 3, 5, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(91, now() - interval '28 days', 'COMPLETED', 'SELF', 3, 2, now() - interval '28 days', 5, now() - interval '28 days', now() - interval '28 days'),
(92, now() - interval '24 days', 'ASSIGNED', 'RECOMMENDED', 3, 5, NULL, NULL, now() - interval '24 days', now() - interval '24 days'),
(93, now() - interval '22 days', 'COMPLETED', 'SELF', 3, 8, now() - interval '22 days', 4, now() - interval '22 days', now() - interval '22 days'),
(94, now() - interval '18 days', 'COMPLETED', 'RECOMMENDED', 3, 9, now() - interval '18 days', 5, now() - interval '18 days', now() - interval '18 days'),
(95, now() - interval '14 days', 'ASSIGNED', 'SELF', 3, 10, NULL, NULL, now() - interval '14 days', now() - interval '14 days'),

-- Dana (user_id: 4)
(4, now() - interval '3 days', 'COMPLETED', 'SELF', 4, 6, now() - interval '3 days', 5, now() - interval '3 days', now() - interval '3 days'),
(17, now() - interval '8 days', 'COMPLETED', 'RECOMMENDED', 4, 7, now() - interval '8 days', 4, now() - interval '8 days', now() - interval '8 days'),
(18, now() - interval '4 days', 'COMPLETED', 'SELF', 4, 10, now() - interval '4 days', 5, now() - interval '4 days', now() - interval '4 days'),
(19, now() - interval '1 day', 'ASSIGNED', 'RECOMMENDED', 4, 3, NULL, NULL, now() - interval '1 day', now() - interval '1 day'),
(46, now() - interval '16 days', 'COMPLETED', 'SELF', 4, 1, now() - interval '16 days', 4, now() - interval '16 days', now() - interval '16 days'),
(47, now() - interval '14 days', 'COMPLETED', 'RECOMMENDED', 4, 8, now() - interval '14 days', 5, now() - interval '14 days', now() - interval '14 days'),
(48, now() - interval '12 days', 'COMPLETED', 'SELF', 4, 2, now() - interval '12 days', 5, now() - interval '12 days', now() - interval '12 days'),
(49, now() - interval '10 days', 'COMPLETED', 'RECOMMENDED', 4, 10, now() - interval '10 days', 5, now() - interval '10 days', now() - interval '10 days'),
(50, now() - interval '6 days', 'COMPLETED', 'SELF', 4, 4, now() - interval '6 days', 4, now() - interval '6 days', now() - interval '6 days'),
(96, now() - interval '20 days', 'COMPLETED', 'RECOMMENDED', 4, 3, now() - interval '20 days', 5, now() - interval '20 days', now() - interval '20 days'),
(97, now() - interval '18 days', 'COMPLETED', 'SELF', 4, 5, now() - interval '18 days', 4, now() - interval '18 days', now() - interval '18 days'),
(98, now() - interval '16 days', 'COMPLETED', 'RECOMMENDED', 4, 7, now() - interval '16 days', 3, now() - interval '16 days', now() - interval '16 days'),
(99, now() - interval '13 days', 'ASSIGNED', 'SELF', 4, 6, NULL, NULL, now() - interval '13 days', now() - interval '13 days'),
(100, now() - interval '11 days', 'COMPLETED', 'RECOMMENDED', 4, 9, now() - interval '11 days', 5, now() - interval '11 days', now() - interval '11 days'),

-- Grace (user_id: 7)
(5, now(), 'ASSIGNED', 'RECOMMENDED', 7, 4, NULL, NULL, now(), now()),
(22, now() - interval '9 days', 'COMPLETED', 'RECOMMENDED', 7, 1, now() - interval '9 days', 4, now() - interval '9 days', now() - interval '9 days'),
(23, now() - interval '6 days', 'COMPLETED', 'SELF', 7, 7, now() - interval '6 days', 4, now() - interval '6 days', now() - interval '6 days'),
(24, now() - interval '3 days', 'COMPLETED', 'RECOMMENDED', 7, 9, now() - interval '3 days', 5, now() - interval '3 days', now() - interval '3 days'),
(25, now() - interval '1 day', 'ASSIGNED', 'SELF', 7, 8, NULL, NULL, now() - interval '1 day', now() - interval '1 day'),
(51, now() - interval '18 days', 'COMPLETED', 'RECOMMENDED', 7, 3, now() - interval '18 days', 5, now() - interval '18 days', now() - interval '18 days'),
(52, now() - interval '15 days', 'COMPLETED', 'SELF', 7, 5, now() - interval '15 days', 4, now() - interval '15 days', now() - interval '15 days'),
(53, now() - interval '12 days', 'COMPLETED', 'RECOMMENDED', 7, 2, now() - interval '12 days', 5, now() - interval '12 days', now() - interval '12 days'),
(54, now() - interval '8 days', 'ASSIGNED', 'SELF', 7, 6, NULL, NULL, now() - interval '8 days', now() - interval '8 days'),
(55, now() - interval '4 days', 'COMPLETED', 'RECOMMENDED', 7, 1, now() - interval '4 days', 4, now() - interval '4 days', now() - interval '4 days'),
(101, now() - interval '23 days', 'COMPLETED', 'SELF', 7, 1, now() - interval '23 days', 5, now() - interval '23 days', now() - interval '23 days'),
(102, now() - interval '20 days', 'COMPLETED', 'RECOMMENDED', 7, 8, now() - interval '20 days', 5, now() - interval '20 days', now() - interval '20 days'),
(103, now() - interval '17 days', 'ASSIGNED', 'SELF', 7, 7, NULL, NULL, now() - interval '17 days', now() - interval '17 days'),
(104, now() - interval '14 days', 'COMPLETED', 'RECOMMENDED', 7, 10, now() - interval '14 days', 5, now() - interval '14 days', now() - interval '14 days'),
(105, now() - interval '11 days', 'COMPLETED', 'SELF', 7, 4, now() - interval '11 days', 4, now() - interval '11 days', now() - interval '11 days'),

-- Henry (user_id: 8)
(6, now() - interval '2 days', 'COMPLETED', 'SELF', 8, 3, now() - interval '2 days', 5, now() - interval '2 days', now() - interval '2 days'),
(10, now(), 'ASSIGNED', 'SELF', 8, 8, NULL, NULL, now(), now()),
(26, now() - interval '8 days', 'COMPLETED', 'SELF', 8, 6, now() - interval '8 days', 5, now() - interval '8 days', now() - interval '8 days'),
(27, now() - interval '5 days', 'COMPLETED', 'RECOMMENDED', 8, 3, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(28, now() - interval '1 day', 'COMPLETED', 'SELF', 8, 10, now() - interval '1 day', 5, now() - interval '1 day', now() - interval '1 day'),
(56, now() - interval '20 days', 'COMPLETED', 'SELF', 8, 6, now() - interval '20 days', 5, now() - interval '20 days', now() - interval '20 days'),
(57, now() - interval '17 days', 'COMPLETED', 'RECOMMENDED', 8, 3, now() - interval '17 days', 5, now() - interval '17 days', now() - interval '17 days'),
(58, now() - interval '14 days', 'COMPLETED', 'SELF', 8, 4, now() - interval '14 days', 4, now() - interval '14 days', now() - interval '14 days'),
(59, now() - interval '11 days', 'COMPLETED', 'RECOMMENDED', 8, 10, now() - interval '11 days', 5, now() - interval '11 days', now() - interval '11 days'),
(60, now() - interval '7 days', 'COMPLETED', 'SELF', 8, 8, now() - interval '7 days', 4, now() - interval '7 days', now() - interval '7 days'),
(106, now() - interval '25 days', 'COMPLETED', 'RECOMMENDED', 8, 3, now() - interval '25 days', 5, now() - interval '25 days', now() - interval '25 days'),
(107, now() - interval '22 days', 'COMPLETED', 'SELF', 8, 6, now() - interval '22 days', 5, now() - interval '22 days', now() - interval '22 days'),
(108, now() - interval '19 days', 'COMPLETED', 'RECOMMENDED', 8, 5, now() - interval '19 days', 4, now() - interval '19 days', now() - interval '19 days'),
(109, now() - interval '16 days', 'ASSIGNED', 'SELF', 8, 8, NULL, NULL, now() - interval '16 days', now() - interval '16 days'),
(110, now() - interval '13 days', 'COMPLETED', 'RECOMMENDED', 8, 2, now() - interval '13 days', 4, now() - interval '13 days', now() - interval '13 days'),

-- Iris (user_id: 9)
(7, now() - interval '5 days', 'COMPLETED', 'RECOMMENDED', 9, 5, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(29, now() - interval '7 days', 'COMPLETED', 'RECOMMENDED', 9, 4, now() - interval '7 days', 4, now() - interval '7 days', now() - interval '7 days'),
(30, now() - interval '3 days', 'ASSIGNED', 'SELF', 9, 9, NULL, NULL, now() - interval '3 days', now() - interval '3 days'),
(61, now() - interval '19 days', 'COMPLETED', 'RECOMMENDED', 9, 1, now() - interval '19 days', 4, now() - interval '19 days', now() - interval '19 days'),
(62, now() - interval '16 days', 'COMPLETED', 'SELF', 9, 7, now() - interval '16 days', 4, now() - interval '16 days', now() - interval '16 days'),
(63, now() - interval '13 days', 'COMPLETED', 'RECOMMENDED', 9, 5, now() - interval '13 days', 5, now() - interval '13 days', now() - interval '13 days'),
(64, now() - interval '10 days', 'ASSIGNED', 'SELF', 9, 8, NULL, NULL, now() - interval '10 days', now() - interval '10 days'),
(65, now() - interval '6 days', 'COMPLETED', 'RECOMMENDED', 9, 6, now() - interval '6 days', 5, now() - interval '6 days', now() - interval '6 days'),
(111, now() - interval '24 days', 'COMPLETED', 'SELF', 9, 4, now() - interval '24 days', 4, now() - interval '24 days', now() - interval '24 days'),
(112, now() - interval '21 days', 'COMPLETED', 'RECOMMENDED', 9, 3, now() - interval '21 days', 5, now() - interval '21 days', now() - interval '21 days'),
(113, now() - interval '18 days', 'ASSIGNED', 'SELF', 9, 10, NULL, NULL, now() - interval '18 days', now() - interval '18 days'),
(114, now() - interval '15 days', 'COMPLETED', 'RECOMMENDED', 9, 9, now() - interval '15 days', 5, now() - interval '15 days', now() - interval '15 days'),
(115, now() - interval '12 days', 'COMPLETED', 'SELF', 9, 2, now() - interval '12 days', 5, now() - interval '12 days', now() - interval '12 days'),

-- Frank (user_id: 6)
(20, now() - interval '5 days', 'COMPLETED', 'SELF', 6, 2, now() - interval '5 days', 4, now() - interval '5 days', now() - interval '5 days'),
(21, now() - interval '2 days', 'ASSIGNED', 'RECOMMENDED', 6, 4, NULL, NULL, now() - interval '2 days', now() - interval '2 days'),
(66, now() - interval '18 days', 'COMPLETED', 'SELF', 6, 1, now() - interval '18 days', 4, now() - interval '18 days', now() - interval '18 days'),
(67, now() - interval '15 days', 'COMPLETED', 'RECOMMENDED', 6, 7, now() - interval '15 days', 4, now() - interval '15 days', now() - interval '15 days'),
(68, now() - interval '12 days', 'ASSIGNED', 'SELF', 6, 5, NULL, NULL, now() - interval '12 days', now() - interval '12 days'),
(69, now() - interval '9 days', 'COMPLETED', 'RECOMMENDED', 6, 8, now() - interval '9 days', 4, now() - interval '9 days', now() - interval '9 days'),
(70, now() - interval '6 days', 'COMPLETED', 'SELF', 6, 9, now() - interval '6 days', 5, now() - interval '6 days', now() - interval '6 days'),
(116, now() - interval '23 days', 'COMPLETED', 'RECOMMENDED', 6, 3, now() - interval '23 days', 5, now() - interval '23 days', now() - interval '23 days'),
(117, now() - interval '20 days', 'COMPLETED', 'SELF', 6, 4, now() - interval '20 days', 4, now() - interval '20 days', now() - interval '20 days'),
(118, now() - interval '17 days', 'ASSIGNED', 'RECOMMENDED', 6, 10, NULL, NULL, now() - interval '17 days', now() - interval '17 days'),
(119, now() - interval '14 days', 'COMPLETED', 'SELF', 6, 7, now() - interval '14 days', 3, now() - interval '14 days', now() - interval '14 days'),
(120, now() - interval '11 days', 'COMPLETED', 'RECOMMENDED', 6, 5, now() - interval '11 days', 4, now() - interval '11 days', now() - interval '11 days'),

-- 추가 다양한 챌린지
(71, now() - interval '13 days', 'COMPLETED', 'RECOMMENDED', 1, 3, now() - interval '13 days', 5, now() - interval '13 days', now() - interval '13 days'),
(72, now() - interval '11 days', 'COMPLETED', 'SELF', 2, 10, now() - interval '11 days', 5, now() - interval '11 days', now() - interval '11 days'),
(73, now() - interval '9 days', 'ASSIGNED', 'RECOMMENDED', 3, 4, NULL, NULL, now() - interval '9 days', now() - interval '9 days'),
(74, now() - interval '7 days', 'COMPLETED', 'SELF', 4, 7, now() - interval '7 days', 3, now() - interval '7 days', now() - interval '7 days'),
(75, now() - interval '5 days', 'COMPLETED', 'RECOMMENDED', 7, 5, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(76, now() - interval '4 days', 'COMPLETED', 'SELF', 8, 3, now() - interval '4 days', 5, now() - interval '4 days', now() - interval '4 days'),
(77, now() - interval '3 days', 'ASSIGNED', 'RECOMMENDED', 9, 6, NULL, NULL, now() - interval '3 days', now() - interval '3 days'),
(78, now() - interval '2 days', 'COMPLETED', 'SELF', 6, 1, now() - interval '2 days', 4, now() - interval '2 days', now() - interval '2 days'),
(79, now() - interval '1 day', 'COMPLETED', 'RECOMMENDED', 1, 2, now() - interval '1 day', 5, now() - interval '1 day', now() - interval '1 day'),
(80, now(), 'ASSIGNED', 'SELF', 2, 4, NULL, NULL, now(), now()),
(121, now() - interval '26 days', 'COMPLETED', 'SELF', 1, 9, now() - interval '26 days', 5, now() - interval '26 days', now() - interval '26 days'),
(122, now() - interval '24 days', 'COMPLETED', 'RECOMMENDED', 2, 3, now() - interval '24 days', 5, now() - interval '24 days', now() - interval '24 days'),
(123, now() - interval '21 days', 'ASSIGNED', 'SELF', 3, 7, NULL, NULL, now() - interval '21 days', now() - interval '21 days'),
(124, now() - interval '19 days', 'COMPLETED', 'RECOMMENDED', 4, 6, now() - interval '19 days', 5, now() - interval '19 days', now() - interval '19 days'),
(125, now() - interval '16 days', 'COMPLETED', 'SELF', 7, 1, now() - interval '16 days', 4, now() - interval '16 days', now() - interval '16 days'),
(126, now() - interval '13 days', 'ASSIGNED', 'RECOMMENDED', 8, 8, NULL, NULL, now() - interval '13 days', now() - interval '13 days'),
(127, now() - interval '11 days', 'COMPLETED', 'SELF', 9, 2, now() - interval '11 days', 5, now() - interval '11 days', now() - interval '11 days'),
(128, now() - interval '8 days', 'COMPLETED', 'RECOMMENDED', 6, 4, now() - interval '8 days', 4, now() - interval '8 days', now() - interval '8 days'),
(129, now() - interval '5 days', 'COMPLETED', 'SELF', 1, 6, now() - interval '5 days', 5, now() - interval '5 days', now() - interval '5 days'),
(130, now() - interval '3 days', 'ASSIGNED', 'RECOMMENDED', 2, 8, NULL, NULL, now() - interval '3 days', now() - interval '3 days'),
(131, now() - interval '13 days', 'ASSIGNED', 'RECOMMENDED', 1, 3, now() - interval '13 days', null, now() - interval '13 days', now() - interval '13 days'),
(132, now() - interval '13 days', 'COMPLETED', 'RECOMMENDED', 1, 3, now() - interval '13 days', 3, now() - interval '13 days', now() - interval '13 days');
