server:
  http_listen_port: 3200

# OTLP 수신
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

# Trace Storage
storage:
  trace:
    backend: s3
    s3:
      endpoint: s3.ap-northeast-2.amazonaws.com
      region: ap-northeast-2
      bucket: onestep-bucket-a508
      prefix: traces/dev
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
      forcepathstyle: true
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

# Metric 생성
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: dev
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    # span-metrics
    span_metrics:
      dimensions:
        - service.name
        - http.method
        - http.status_code
        - http.route
    # service-graphs
    service_graphs:
      dimensions:
        - service.name

# Loki
overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics