spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/onestep?options=-c%20timezone%3DAsia%2FSeoul
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 580000
      leak-detection-threshold: 10000

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  jwt:
    access:
      expiration: 604800
    refresh:
      expiration: 604800 

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: onestep-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.a508.onestepapi.kafka.dto.KafkaMessageDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: onestep-api

openapi:
  base-url: http://${SERVER_IP}:8080