name: Deploy FastAPI
on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE_CONTENTS }}" > docker/dev/.env

      # Docker login
      - name: Docker Login to GHCR
        run: echo ${{ secrets.YY_GITHUB_PAT }} | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

      # Image Build and Push
      - name: Build and Push Docker Image
        run: |
          cd fastapi
          docker build -t ghcr.io/youyeon11/fastapi-app:latest .
          docker push ghcr.io/youyeon11/fastapi-app:latest

  transfer:
    name: Transfer
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Transfer docker file
      - name: Transfer docker-compose.dev.yaml file & deploy script to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./docker/dev/
          target: /home/ubuntu/

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: transfer
    steps:
      - name: SSH into EC2 server and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > /home/ubuntu/docker/dev/.env

            echo "${{ secrets.YY_GITHUB_PAT }}" | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

            docker compose -f /home/ubuntu/docker/dev/docker-compose.dev.yaml down fastapi-app || true
            docker compose -f /home/ubuntu/docker/dev/docker-compose.dev.yaml pull fastapi-app
            docker compose -f /home/ubuntu/docker/dev/docker-compose.dev.yaml up --no-deps -d fastapi-app

            docker image prune -f
